name: BlockTyper
version: 0.0.1
main:  com.blocktyper.BlockTyperPlugin
author: spaarkimus
website: blocktyper.com
database: false
description: Create teams and bases.  Lay siege on other teams' bases.
commands:
  superpower:
    description: makes you like totally awesome brah!!!
  sp:
    description: makes you like totally awesome brah!!!